=======================================================
psycopg2.InterfaceError: connection already closed
2023-04-11 09:40:36,951 10900 INFO turbo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 7 connections

2023-04-11 09:40:13,759 10900 WARNING turbo odoo.addons.base.models.ir_ui_view: View edin_service.view_move_form_edin: Full path [edin_service/views/account_move.xml] cannot be found.

ну тут или у тебя все коннекты забиты, их можно очистить попробовать через базу данных напрямую! или в конфиге попробовать увеличить количество подключений к базе
в postgresql.conf


Ошибка InterfaceError: connection already closed обычно возникает при попытке доступа к базе данных через ORM (Object Relational Mapping) в Odoo,
когда соединение с базой данных уже было закрыто или прервано.

Приведу несколько рекомендаций, которые можно выполнить, чтобы решить эту ошибку:

Проверьте наличие активного подключения к базе данных:
Убедитесь, что у вас есть активное подключение к базе данных перед выполнением операции.
 Если подключение было закрыто или прервано, необходимо установить новое подключение перед выполнением операции.
 Пример использования контекста подключения:

with api.Environment.manage():
    with api.Environment('your_database_name').cursor() as cr:
        env = api.Environment(cr, self.env.uid, self.env.context)
        # Ваш код для выполнения операции с базой данных
Проверьте наличие открытых транзакций: Если у вас есть открытые транзакции, и вы пытаетесь выполнить операции с базой данных, такие как запись или чтение, возможно, ошибка происходит из-за уже открытой транзакции. В таком случае, закройте или подтвердите текущую транзакцию перед выполнением операции.
python
Copy code
self.env.cr.commit()  # Закрытие текущей транзакции
Проверьте наличие активных сессий: Если у вас есть активные сессии в системе, и вы пытаетесь выполнить операции с базой данных в контексте этих сессий, возможно, ошибка происходит из-за неправильного использования или закрытия сессий. Убедитесь, что вы правильно открываете, закрываете или обновляете сессии в соответствии с правилами Odoo.

Проверьте наличие внешних подключений: Если вы используете внешние подключения к базе данных, такие как подключение к другой базе данных или сторонним сервисам, убедитесь, что подключения правильно устанавливаются и закрываются после использования, чтобы избежать ошибок закрытого подключения.
